export const FETCH_ACCOUNT_SETTINGS_REQUEST = 'FETCH_ACCOUNT_SETTINGS_REQUEST';
export const FETCH_ACCOUNT_SETTINGS_SUCCESS = 'FETCH_ACCOUNT_SETTINGS_SUCCESS';
export const FETCH_ACCOUNT_SETTINGS_ERROR   = 'FETCH_ACCOUNT_SETTINGS_ERROR';

export const UPDATE_ACCOUNT_SETTINGS_REQUEST = 'UPDATE_ACCOUNT_SETTINGS_REQUEST';
export const UPDATE_ACCOUNT_SETTINGS_SUCCESS = 'UPDATE_ACCOUNT_SETTINGS_SUCCESS';
export const UPDATE_ACCOUNT_SETTINGS_ERROR   = 'UPDATE_ACCOUNT_SETTINGS_ERROR';

export const SEND_REPORT_REQUEST = 'SEND_REPORT_REQUEST';
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS';
export const SEND_REPORT_ERROR   = 'SEND_REPORT_ERROR';
