export const CONNECT_BROKER_REQUEST     = 'CONNECT_BROKER_REQUEST';
export const CONNECT_BROKER_SUCCESS     = 'CONNECT_BROKER_SUCCESS';
export const CONNECT_BROKER_ERROR       = 'CONNECT_BROKER_ERROR';
export const DISCONNECT_BROKER          = 'DISCONNECT_BROKER';
export const NETWORK_STATUS_UPDATE      = 'NETWORK_STATUS_UPDATE';
export const CONNECT_LOST               = 'CONNECT_LOST';
export const CONNECT_RESTORE            = 'CONNECT_RESTORE';
export const RECONNECT_BROKER_SUCCESS   = 'RECONNECT_BROKER_SUCCESS';
export const DISCONNECT_MESSAGE_TIMEOUT = 2 * 1000;     // eslint-disable-line no-magic-numbers

export const GET_MQTT_CREDENTIALS_REQUEST = 'GET_MQTT_CREDENTIALS_REQUEST';
export const GET_MQTT_CREDENTIALS_SUCCESS = 'GET_MQTT_CREDENTIALS_SUCCESS';
